### ISSUE TITLE
Error when submit the form with city='

### ISSUE THREAD

**Issue by hrrmsn** [hrrmsn/appform#13]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/hrrmsn/Plan9/dev/languages/python/magnit_test_problem/code/appform/appform.py", line 208, in app
    handle_post(environ)
  File "/home/hrrmsn/Plan9/dev/languages/python/magnit_test_problem/code/appform/appform.py", line 189, in handle_post
    cityid = get_areaid('city', parsed_data)
  File "/home/hrrmsn/Plan9/dev/languages/python/magnit_test_problem/code/appform/appform.py", line 176, in get_areaid
    sql_statements=[(sql_statement, )]
  File "/home/hrrmsn/Plan9/dev/languages/python/magnit_test_problem/code/appform/appform.py", line 68, in db_request
    db_response = cur.execute(sql_instruction, parameters)
OperationalError: unrecognized token: "'''"

```

**Comment by hrrmsn** [comment]
**DONE.**
