### ISSUE TITLE
Problems with encoding

### ISSUE THREAD

**Issue by hrrmsn** [hrrmsn/appform#20]
```
[2017-05-24 13:30:52 +0000] [364] [ERROR] Error handling request /view
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/hrrmsn/Plan9/dev/languages/python/magnit_test_problem/code/appform/main.py", line 119, in app
    return func(environ, start_response)
  File "/home/hrrmsn/Plan9/dev/languages/python/magnit_test_problem/code/appform/view.py", line 70, in view
    'tbody': users_table_body(persons_data),
  File "/home/hrrmsn/Plan9/dev/languages/python/magnit_test_problem/code/appform/view.py", line 42, in users_table_body
    table_body += '<td>{}</td>'.format(person[column] if person[column] else '<i>N/A</i>')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0439' in position 0: ordinal not in range(128)
[2017-05-24 13:31:02 +0000] [364] [DEBUG] Closing connection. 
[2017-05-24 13:31:02 +0000] [364] [DEBUG] Closing connection. 
[2017-05-24 13:31:02 +0000] [364] [DEBUG] Closing connection. 
[2017-05-24 13:31:02 +0000] [364] [DEBUG] Closing connection. 

```

**Comment by hrrmsn** [comment]
Read first.
https://docs.python.org/2.7/howto/unicode.html

Helpful article. (Read second.)
https://nedbatchelder.com/text/unipain.html

**Comment by hrrmsn** [comment]
```
[2017-05-24 14:07:02 +0000] [1446] [ERROR] Error handling request /view
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/hrrmsn/Plan9/dev/languages/python/magnit_test_problem/code/appform/main.py", line 112, in app
    post.handle_post(environ)
  File "/home/hrrmsn/Plan9/dev/languages/python/magnit_test_problem/code/appform/post.py", line 61, in handle_post
    commit_required=True
  File "/home/hrrmsn/Plan9/dev/languages/python/magnit_test_problem/code/appform/tools.py", line 33, in db_request
    db_response = cur.execute(sql_instruction, parameters)
ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.

```
